### ISSUE TITLE
Overflow in lib.rs

### ISSUE THREAD

**Issue by Minhyeok01** [10XGenomics/rust-boomphf#15]
Hello.

When I run the example code, overflow occurs on line 75 of lib.rs.

It seems to be a problem caused by setting 1 to i32 in rust by default. Is there a solution?

**Comment by pmarks** [comment]
@Minhyeok01 interesting. What platform are you using? Is usize 32bits?

Can you try changing the hashmod function to this:
```rust
#[inline]
fn hashmod<T: Hash>(iter: u64, v: &T, n: usize) -> u64 {
    // when n < 2^32, use the fast alternative to modulo described here: 
    // https://lemire.me/blog/2016/06/27/a-fast-alternative-to-the-modulo-reduction/
    if n <= 0xFFFFFFFF { 
        let h = hash_with_seed32(iter, v);
        fastmod(h, n as u32) as u64
    } else {
        let h = hash_with_seed(iter, v);
        h % (n as u64)
    }
}
```

**Comment by Minhyeok01** [comment]
Thank you for answer.

After fixing it according to the solution you answered, the overflow disappeared from lib.rs. But another overflow ('attempt to shift left with overflow') occurred on line 358 of bitvector.rs. 

Is there something I am missing or  wrong when running?

I use 64bit window and ubuntu for os and vim for editer.

**Comment by pmarks** [comment]
@Minhyeok01 I think you must be using a 32bit target somehow -- both of these issues are related to usize being 32bits instead of 64 bits.  I will work on fixing the 32bit correctness but there are a few things to change and it will probably take me a few days.

**Comment by Minhyeok01** [comment]
@pmarks  Thank you for answer. Your answer helped me a lot.

**Comment by Minhyeok01** [comment]
@pmarks  I guess my compiler recognizes 1 and other integers as i32.

This modification runs well:
#[inline]
fn word_mask(index: usize) -> (usize, usize) {
    let word = index / 64;
    let mask = (1_usize) << (index % 64);
    (word, mask)
}
