### ISSUE TITLE
Contradicting docs for NoKeyBoomHashMap

### ISSUE THREAD

**Issue by domma** [10XGenomics/rust-boomphf#34]
Looking at the docs for [NoKeyBoomHashMap](https://10xgenomics.github.io/rust-boomphf/master/boomphf/hashmap/struct.NoKeyBoomHashMap.html) I read at the top:

> ... but can only be used if you can guarantee that you will only query for keys that were in the original set. Querying for a new key will return a random value, silently.

But the doc string for `get` says:

> Get the value associated with key, if available, otherwise return None

To me this sounds like a contradiction. If the hash map is build based on a set of keys (and values) all of those must be present. Can somebody explain what I'm missing?

**Comment by pmarks** [comment]
Thanks for pointing this out, the docstring for `get` is definitely misleading.  If you pass some new key to `get` that wasn't used at construction time, you will get some random sample of either `Some()` with a random item, or None`.  If you use a valid key, you will get the right answer. I will update the docs to be clearer.
