### ISSUE TITLE
Overflows in 32 bit target

### ISSUE THREAD

**Issue by ozgrakkurt** [10XGenomics/rust-boomphf#36]
There are a bunch of overflows because of the usage of `usize` and not considering `usize` can be 32bits.

steps to reproduce:
- `cargo install cargo-wasi`
- `cargo wasi run` in a project that uses the filter

Or probably can just run tests on x86 32bit target using something like [this](https://github.com/ozgrakkurt/sbbf-rs/blob/6c9cfc14d04fc6b06f42fc09057572ec548607c3/.github/workflows/ci.yaml#L33)

**Comment by pmarks** [comment]
fixed in #28 - will do a new release to crates.io soon
