### ISSUE TITLE
Mphf Clone

### ISSUE THREAD

**Issue by Tockra** [10XGenomics/rust-boomphf#7]
Hey,

is there a reason why the Mphf struct didn't implement the clone trait?

T

**Comment by Tockra** [comment]
At the moment I'm not able to start a pull request. But I thought about something like that: 
https://github.com/Tockra/rust-boomphf

I'm not sure if ` AtomicUsize::new(x.load(Ordering::Relaxed).clone()))` is the right way to clone. 
I just need to test it.

**Comment by pmarks** [comment]
@Tockra sure, a PR would be great, thanks!

**Comment by Tockra** [comment]
So I did it: https://github.com/10XGenomics/rust-boomphf/pull/8 but perhabs somebody should write some tests. I don't know enough about the Send aspect.

**Comment by Tockra** [comment]
I think the actual version should run. But I'm not realy sure if the `Ordering::SeqCst` is needed realy or `Ordering::Relaxed` could run too. 
In my opinion I need a `Ordering::SeqCst` but I don't know what happening in `new_parallel`. 
Maybe the other `Ordering::Relaxed` in `bitvector.rs` are problematic, but I don't know ...

**Comment by pmarks** [comment]
Fixed in #8. Thanks!
